project:
  type: website
  output-dir: docs

website:
  title: "RNA-seq data analysis workflow"
  favicon: theme_images/GA-image-black-favicon.png
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  sidebar:
    style: "docked"
    contents:
      - text: "Home"
        href: index.qmd
      - text: "Background"
        href: background.qmd
      - text: ""
        href: episode_1.qmd
      - text: ""
        href: episode_2.qmd
      - text: ""
        href: episode_3.qmd
      - text: ""
        href: episode_4.qmd
      - text: ""
        href: episode_5.qmd
      - text: ""
        href: episode_6.qmd

    tools:
      - icon: github
        text: Github
        href: https://github.com/otagobioinformaticsspringschool/RNA-seq-data-analysis-workflow

format:
  html:
    mainfont: "Mukta"
    monofont: "monospace"
    fontsize: 20px
    css: styles.css
    navigation: true
    page-navigation: true
    toc: true
    toc-location: right
    toc-depth: 3
    toc-title: "Contents"
    code-copy: true
    code-block-bg: true

